#File handling operations
#MAIN PROGRAM
print("Enter how many students' data you want to write into the file?:")
n=int(input())
f=open("test.txt","w")
for i in range (n):
    print("Enter Student",i+1,"name:")
    a=input()
    f.writelines("Student name:\t")
    f.writelines(a)
    print("Enter Student",i+1,"Rollno:")
    b=input()
    f.writelines("\nStudent rollno:\t")
    f.writelines(b)
    print("Enter Course pursued by the student:")
    c=input()
    f.writelines("\nStudent course:\t")
    f.writelines(c)
    print("Enter College name:")
    d=input()
    f.writelines("\nStudent College:\t")
    f.writelines(d)
f.close()
print("Contents of file:")
f=open("test.txt",'r')
contents=f.read()
print(contents)
